### ISSUE TITLE
Delet or make Inscription Stamp a focus recipe

### ISSUE THREAD

**Issue by DaedalusGame** [DaedalusGame/Soot#90]

**Comment by SirAron111** [comment]
This should get a higher priority on your to-do list mate its confusing the heck out of players if every recipe shows the stamper in jei as first thing. Especially the judger ones who can’t read the translations so well keep reporting to me that X recipe don’t work they can’t find the stomper …

**Comment by DaedalusGame** [comment]
it's so low on the list because this recipe was introduced 11 months ago and nobody complained until april of this year

**Comment by SirAron111** [comment]
I should have complained earlier than XD. No seriously literally every item gets this recipe added trough jei as they all register I think not adding it as a listed recipe and just making a little notice in the ancient codex saying hey you can also simply rename literally every existing item in the game with this stamper like you can with the anvil. (Anvil recipe also doesn’t register in jei for everything)
The people from jei said it needs to be changed from the mod its coming from so it must be this one.
I hope its easily fixed since I don’t want to bother you. But I do get a lot of people asking stuff like I can’t make the hand crank of x or I can’t make the whatever item for this and they tell me they try to use the recipe from the stopper as this is the first to show up or even if the item is uncraftable that recipe still shows up and they complain why can’t I make x creative item there is a recipe for it with a stamper and stuff.
And most of all its actually rather laggy on recipe loading since it gets added to every items recipe list.
This problem wasn’t here when I tried to remove this mod but I don’t want to have to removed it since it adds useful stuff to embers.

**Comment by DaedalusGame** [comment]
it's not as easy of a fix as I'd have hoped, and i have a mountain of other changes that must be finished before i can push a new version so the situation is a bit demotivating. basicly i need to add support in embers to extend hidden recipe support from just anvil recipes to other types.

**Comment by TheXTrunner** [comment]
will this ever get fixed?
